UPDATE sprintboarditems
SET notes = notes || '

--- REVISED PLAN (2026-08-26): queue-competition check + raised checkpoint + corrected Step 4 estimate ---

TASK 1 -- QUEUE COMPETITION, code-confirmed, plain answer: NO dedicated priority exists. runPhase3''s SELECT has no ORDER BY differentiating reset rows from anything else -- it just re-checks current state (lei_status IS NULL OR all-three-parent-chain-fields-null) via idx_entity_master_phase3, scanned in LEI-ascending order (confirmed via EXPLAIN QUERY PLAN in the prior session). Reset rows re-enter the exact same undifferentiated pool as any other currently-eligible entity, including new ones added later (e.g. future FIRDS ingestion).

QUANTIFIED, and this materially changes the estimate: of the 6,265 reset-target rows, only 264 sort strictly before the rest-of-pool''s minimum LEI (guaranteed-first, no competition). The remaining 6,001 (96%) are interleaved with the ~10,156-entity rest-of-pool, and critically the reset target''s own max LEI (ZYXJDNVM2JI3VBM8G556) sorts AFTER the rest-pool''s entire max (ZR7XWIN3GSRDDWZ9V446) -- meaning the scan must drain nearly the ENTIRE combined pool before the LAST reset row is guaranteed cleared, not just 6,265 entities'' worth of invocations. Post-reset combined eligible pool = 10,156 + 6,265 = 16,421.

TASK 2 -- CHECKPOINT RAISED: SUBREQUEST_CHECKPOINT 40 -> 44. Reasoning: worst-case final subrequestCount = (threshold-1)+3 = threshold+2 (corrected an arithmetic slip in the original comment, which said 39+3=43 for threshold=40 -- actually 42; the deployed behavior was still safe, just mis-stated by 1). threshold=48 would be the mathematical max (worst-case exactly 50, zero margin). Chose 44 (worst-case 46, a real 4-subrequest margin) rather than the max: the original conservative margin addressed "is a checkpoint trip costly" (now proven no -- clean defer-and-requeue, confirmed via the earlier parallel check), but Step 1''s separate, still-unresolved finding (this counter can undercount if fetch() itself throws on a genuine platform "Too many subrequests", as opposed to an ordinary HTTP error status) is a different risk not retired by proving defer is safe -- so some margin was deliberately kept rather than maxing out. Deployed: meridian-entities-enrich version d7b9b2ba-fffc-40ab-943a-8a00c00570d3, both crons confirmed active. Live-verified at the real :50+ dispatch window (fired at minute=54 after an unexpectedly long background-execution delay, not a code issue): real result 44 subrequests, 42 entities attempted, 3 deferred (42+3=45, full batch) -- checkpoint fired exactly at its new threshold, real throughput improved from 38 to 42 entities/invocation.

REVISED STEP 4 ESTIMATE: using real throughput (42/invocation) against the corrected combined-pool understanding (16,421, not 6,265) from Task 1: invocations needed = ceil(16421/42) = 391 (up from the prior estimate''s 165). Optimistic wall-clock (no Sunday skips): 391 calendar days (~12.9 months). Realistic (accounting for the still-live Sunday collision pattern, Known Issue 22.12): ~457 calendar days (~15.0 months). This is roughly 2.5-3x longer than the previous estimate, entirely because that estimate incorrectly assumed the 6,265 reset rows would get processed in isolation rather than diluting into the much larger general pool. Total real D1 write cost (reset + reprocessing) is largely unchanged from the prior estimate (~25,000-28,000 total, since that was already counting each entity individually, not per-invocation) -- what changed is purely the TIMELINE, not the total write volume.

FLAGGING FOR FOUNDER DECISION, not resolved here: at ~13-15 months to fully clear, is this reset-and-let-cron-drain-it approach still the right one, or does the corrected timeline change the calculus toward e.g. a dedicated/prioritized batch specifically for the reset rows (a real code change, not yet scoped), a higher per-day invocation count (a cron-cadence change, its own three-point check), or accepting the multi-year-adjacent timeline as-is given this is non-blocking backfill data quality, not user-facing urgency. Not deciding this unilaterally -- reporting the corrected numbers for review.

STILL NOT DONE, correctly not started: Step 5 (execute the reset). Awaiting review of this revised estimate before reconsideration.'
WHERE ticket_id = 'MA-SEP-009';
