UPDATE sprintboarditems
SET notes = notes || '

--- STEP 4 RESULT (2026-08-24, budget estimate only, no writes/reset executed) ---
RESET TARGET, precisely re-confirmed (not assumed unchanged): exactly 6,265 rows have direct_parent_exception=NO_LINK_DECLARED with updated_at < 2026-08-24 -- the original, frozen-since-diagnosis set. Separately, 86 NEW exceptions were correctly written today by the FIXED code (real GLEIF answers) -- these are correct and must NOT be included in the reset (verified via updated_at filtering, not assumed).

Q1 -- INVOCATIONS NEEDED: real observed checkpoint-governed throughput is 38 entities/invocation (hardening test, live-measured, not assumed). 6,265 / 38 = 165 invocations (ceiling). Real throughput may vary slightly with hit-rate (more real relationships found per batch consumes more subrequests per entity, lowering entities/invocation before the 40-subrequest checkpoint trips) -- 38 is used as the anchor since it is the only real measured number available under the deployed checkpoint.

Q2 -- REAL D1 WRITE BUDGET, reasoned from the live schema (no test writes performed, per instruction -- entity_master has 9 real secondary indexes, confirmed live; entity_relationships has 3 -- PK autoindex + idx_entity_rel_child + idx_entity_rel_parent). Reset UPDATE only touches direct_parent_exception (covered by idx_entity_master_phase3, a composite index) and updated_at (unindexed) -- real cost ~2 writes/row (base row + that one covering index), NOT the full 9x an INSERT would cost, since UPDATE only maintains indexes on columns that actually changed. One-time reset UPDATE (single batched statement, 6,265 rows): ~12,530 real D1 writes. Reprocessing cost per entity depends on outcome: exception (same shape as reset) ~2 writes; a real relationship found costs more -- entity_relationships INSERT ~4 writes (base + 3 indexes) + entity_master mirror UPDATE ~3 writes (base + the specific parent-LEI index + idx_entity_master_phase3) = ~7/relationship, doubled if both direct- and ultimate-parand differ; a genuinely NEW parent entity (INSERT, not UPDATE) costs ~10 writes (base + up to 9 indexes), but real observed data show this is rare (1 new-parent creation in ~83 real attempts so far, ~1.2%). Applying the real observed overall hit-rate (~5-6 real relationships per 83 real attempts, ~6-7%) against 6,265 rows: reprocessing cost range ~12,530 (floor, if this backlog behaves like the broader 30-entity general-population sample that showed 0% real hits during original diagnosis) to ~15,160 (upper, if it behaves like the recent FIRDS-heavy test batches at ~6% hit rate) real writes. TOTAL across the whole undertaking (one-time reset + full reprocessing): ~25,060 to ~27,690 real D1 writes. Checked against caps: the account-wide shared 100,000/day cap comfortably absorbs either the one-time reset (~12,530, so long as it does not land on a day already heavy from another writer -- see Q4) or any single day''s reprocessing batch (~70-115 writes/day, trivial). entities-enrich''s own 5,000-headroom checkWriteBudget guard does NOT gate the manual reset UPDATE itself (that check only runs inside the Worker''s own dispatcher, not an ad-hoc SQL statement run directly) -- the reset must be manually scheduled on a day/time with real confirmed headroom, same discipline as every prior live test this packet has used.

Q3 -- REALISTIC WALL-CLOCK ESTIMATE: at the existing once/day cadence (50 6 * * *), 165 invocations needed. Optimistic (assuming every day fires successfully): 165 calendar days (~5.4 months). Realistic, accounting for the still-live Sunday collision pattern (Known Issue 22.12 -- meridian-holdings'' accelerating weekly write volume, 28,106 -> 60,304 -> 74,778 -> 98,651 across 4 tracked Sundays, already empirically confirmed to have blocked an entities-enrich run once on 2026-08-23): assume roughly 1-in-7 calendar days (Sundays) gets skipped by entities-enrich''s own write-budget guard correctly self-deferring -- pushes the realistic estimate to ~193 calendar days (~6.3 months). This is NOT a quick backfill -- it is a multi-month, cron-paced undertaking by design, matching the Founder''s own decision to keep BATCH=45 and rely on the in-loop checkpoint rather than a bigger batch or a burst mode.

Q4 -- SHARED-CAP RISK FOR OTHER JOBS: daily reprocessing volume (~70-115 writes/day) is trivial against the shared 100,000/day cap and poses no meaningful risk to other Entities- or ETF-domain jobs on a normal day. The ONE-TIME reset UPDATE (~12,530 writes in one statement) is meaningfully larger than any single day''s normal reprocessing traffic and must be deliberately scheduled on a non-Sunday day with real confirmed headroom immediately beforehand (same live-headroom-check discipline used before every /run trigger so far in this packet) -- do not run it on or adjacent to a Sunday given meridian-holdings'' pattern. Ongoing risk for the ~193-day reprocessing tail: none beyond what already exists today (Sundays already collide; this reset does not materially change that dynamic since its own daily footprint is trivial) -- the real, standing risk is Known Issue 22.12 itself (meridian-holdings'' unreviewed, accelerating weekly cadence), not this reset.

NOT YET DONE, correctly not started per instruction: Step 5 (execute the reset). Awaiting review of this estimate.'
WHERE ticket_id = 'MA-SEP-009';
