UPDATE sprintboarditems
SET blocker = NULL,
    notes = notes || '

--- HARDENING STEP RESULT (2026-08-24, real in-loop subrequest checkpoint) ---
STEP 1 (silent-swallow check): No historical Cloudflare log/exception access was available -- wrangler only offers `wrangler tail` (live streaming only, confirmed via --help, no historical query subcommand exists), and logging into the Cloudflare dashboard directly was not attempted (would require entering account credentials, which is out of bounds). Used indirect D1-state forensics instead: isolated the exact 43 entity_master rows touched by the prior 05:50 UTC test run via updated_at window, found 42 reached a clean terminal state (real parent or exception correctly written) and 1 was a newly-created PARENT entity (Ninety One Global Strategy Fund, a legitimate byproduct of the fix''s create-parent-if-missing path, not one of the 45 selected/primary entities). Cross-referencing against the known batch size of 45: 45 - 42 clean primary entities = 3 primary entities that produced ZERO database writes at all -- no Level-1 update, no exception marker, nothing. This is CONSISTENT WITH (though not conclusively proven to be) a request failing silently inside runPhase3''s existing try/catch before any write occurred -- possibly the exact "Too many subrequests"-style failure asked about, possibly an ordinary GLEIF-side HTTP/network error, indistinguishable from available evidence. Reported explicitly, not assumed away: today''s 4-real-parent, 50-subrequest result may understate the true hit rate/true subrequest attempt count by an unknown, non-zero amount.

STEP 2 (checkpoint implementation): Added SUBREQUEST_CHECKPOINT = 40 inside runPhase3, checked before starting each new entity in the loop (mirrors holdings-pipeline.js''s per-item guard pattern, checking before starting new work rather than only bounding via an outer batch constant). BATCH stays 45, unchanged, per Founder decision. Threshold reasoning: each entity costs up to 3 fetches (1 self-detail + up to 2 relationship-resolve follow-ups). A pure "before starting a new entity" checkpoint at 40 bounds the true worst case to 39 + 3 = 43 -- but given Step 1''s real, unresolved uncertainty about possible undercounting, deliberately went below the minimal-viable threshold (45 would have given 44+3=47, still under 50) to bank real margin against exactly the kind of silent-failure risk Step 1 could not rule out. On-deferral, remaining batch entities are left completely untouched (no partial write), so they simply match Phase 3''s own WHERE clause again on the next invocation -- queued, not dropped.

STEP 3 (live verification, not just a diff read): Deployed, then triggered a real /run at the actual 06:50 UTC dispatch window against a real 45-entity batch drawn from the live 10,323-entity eligible pool. Real, persisted result: enrich_phase3_last_run_entities (attempted) = 38, enrich_phase3_last_run_deferred = 7 (38+7=45, confirms the full selected batch is accounted for), enrich_phase3_last_run_subrequests = enrich_combined_last_invocation_subrequests = 40 -- the checkpoint fired at exactly its configured threshold, live, in production, and correctly stopped before starting entity #39 rather than exceeding it. This is real evidence the guard works as designed, not an assumption from reading the code.

STEP 4 (redeploy): meridian-entities-enrich redeployed, version ba5af420-d953-46b2-a8d9-979fb9f45865. Both crons confirmed active post-deploy: schedule 0 6 * * * (Phase 1) and schedule 50 6 * * * (Phase 2+3) -- wrangler deploy output showed both listed after upload, and the subsequent live /run trigger at the 06:50 window firing correctly is itself further confirmation the deployment is live and correct.

MINOR ASIDE, not blocking: confirmed entities-enrich.js only ever READS writes_today_<date> (via checkWriteBudget) -- it never increments/contributes to that shared counter itself, unlike holdings-pipeline.js which explicitly does. Not this packet''s concern to fix, noted for completeness only.

Not yet done, correctly not started per instruction: Step 3 of the overall MA-SEP-009 packet (INSERT-path test on a small controlled case), the 6,265-row reset budget estimate, and the reset itself. Awaiting review of this hardening step before proceeding.'
WHERE ticket_id = 'MA-SEP-009';
