UPDATE sprintboarditems
SET notes = notes || '

--- OPERATIONAL SIDE-FINDING (2026-08-23, Tech Ops/SRE, read-only investigation) ---
WHAT CONSUMED TODAY''S WRITE BUDGET (98,651 of 100,000 as of the Phase 2+3 dispatch window): identified as meridian-holdings (App/ETF Refresh/src/holdings-pipeline.js), a chunked/resumable N-PORT fund-holdings refresh job. holdings_pipeline_state.last_full_run = 2026-08-23T04:00:25.008Z matches exactly the timestamp fund_holdings_monthly (3,298 new rows) and fund_snapshot_monthly (4 new rows) were written today, both within an 8-second window (04:00:27-04:00:35). etf_master/universe_changes_monthly/entity_exposure_monthly/fund_exposure_coverage all show zero writes today -- this run never reached those downstream steps. fund_holdings_monthly carries 7 indexes; the pipeline''s own code comment documents an empirically-confirmed ~9x real-rows_written-per-logical-row multiplier on this table -- logical row counts alone badly understate true D1 write cost here, consistent with why the account-wide total (98,651) is far higher than the ~3,300 logical rows written.

IS THIS EXPECTED OR ANOMALOUS -- ANSWER: WEEKLY AND EXPECTED IN SCHEDULE, BUT ON A REAL, UNEXPLAINED GROWTH TREND. wrangler-holdings.toml''s cron is 0 4 * * 0 -- Sundays, 04:00 UTC ONLY, not daily. Confirmed 2026-08-23 is itself a Sunday, and the toml''s own comment documents why: originally every-2-hours (0 */2 * * *), which caused 100k+ rows_written/day despite an 80k guard (a guard-failure bug, MA-AUG-002 diagnostic) -- emergency-mitigated to weekly-only on 2026-07-28, changed directly in the Cloudflare dashboard first, config file updated after the fact, and explicitly flagged in that same comment as "not yet reviewed by Architect/ETF Product Lead as a permanent cadence" -- a stopgap that has now run unreviewed for almost a month. holdings_pipeline_state''s full writes_today_* history (18 dated entries found, back to 2026-06-07) independently confirms this: the 2026-07-25 through 2026-07-28 cluster (93,412 / 104,694 / 77,206 / 107,693 -- two days already over the 100k cap) matches the pre-fix every-2-hours era exactly. Every large spike since the 07-28 fix lands on a Sunday: 08-02 (28,106), 08-09 (60,304), 08-16 (74,778), 08-23 (98,651, today) -- four consecutive Sundays, a clean and complete pattern, no daily-collision counterexample found in the data on any non-Sunday day since the fix.

THE GROWTH TREND ITSELF IS THE REAL FLAG: 28,106 -> 60,304 -> 74,778 -> 98,651 across those four Sundays is a clear, accelerating rise, not a stable weekly cost -- today''s figure alone is a hair under the shared 100,000 cap, before any other Worker (including entities-enrich) writes anything. Root cause of the acceleration not fully confirmed (out of scope to modify/dig further into ETF-domain internals this session, read-only per instruction) -- most likely explanation, circumstantial not proven: the pipeline is chunked/resumable and stateful (etf_offset persists across invocations, PIPELINE_BATCH_SIZE=20 ETFs attempted/invocation, only resets to 0 once the full ~237-series-eligible universe is completed in one continuous pass) and has NEVER once finished a full pass since the weekly cadence began -- today''s run stopped again mid-batch (last_run_status = running:213/237:partial:3, meaning 213 of 237 eligible series done, this invocation completed 17 of a 20-ETF batch before its own internal 80,000-write guard tripped, 3 left partial) -- consistent with per-ETF write cost itself growing over time as more months of N-PORT filing history accumulate in fund_holdings_monthly, so the same fixed 80,000-write guard buys a shrinking number of completed ETFs each week and the account-wide total creeps upward. Flagged as the leading hypothesis, not confirmed fact.

SCHEDULING COLLISION RISK -- REAL BUT WEEKLY, NOT DAILY: entities-enrich''s own cron (50 6 * * *) fires DAILY, including Sundays, at 06:50 UTC -- just under 3 hours after meridian-holdings'' 04:00 UTC Sunday fire. Six days out of seven the shared write budget is untouched by meridian-holdings when entities-enrich''s Phase 2+3 runs; on Sundays specifically the two jobs now genuinely compete for the same shared account-wide 100,000-write cap, and today''s collision (which blocked MA-SEP-009''s own Step 2 bounded-batch subrequest test) is real, reproducible evidence of that, not a one-off fluke -- confirmed by a real writes_today value already at 98,651 before entities-enrich''s window even opened. Given the accelerating trend, this is worth actively scheduling around rather than assuming it self-resolves: either move entities-enrich''s Sunday-specific run to a time comfortably clear of meridian-holdings'' 04:00 UTC window (a scheduling change, not a code change, and still subject to CLAUDE.md''s three-point check / change-request discipline for any cron edit), or treat it as a standing reason entities-enrich''s Sunday cron fire may need to tolerate a skipped/deferred run some weeks via its own existing write-budget guard (which is already working as designed -- it correctly declined to run today rather than risk exceeding the shared cap). Recommend flagging meridian-holdings'' still-unreviewed "emergency mitigation" cadence to the Architect/ETF Product Lead independently of MA-SEP-009 -- it has been running un-reviewed for a month and is the actual root driver of this collision risk, not something Entities-domain can fix on its own side.'
WHERE ticket_id = 'MA-SEP-009';
