UPDATE sprintboarditems
SET notes = notes || '

--- PARALLEL CHECK + STEP 3 RESULT (2026-08-24) ---
PARALLEL CHECK (the 3-of-45 zero-write entities): could not pinpoint the exact 3 entity_ids -- used the confirmed idx_entity_master_phase3 (LEI-ascending) index scan order to reconstruct the batch window precisely, but the reconstructed window (42 batch rows + 20 unrelated pre-existing rows, all 62 accounted for) shows zero gaps, and nothing eligible sits just outside either edge. No historical Cloudflare log access exists to resolve this further (wrangler tail is live-only, confirmed via --help). Reported as a real limitation, not glossed over. HOWEVER the actual question (self-healing vs real silent-loss bug) has a complete code-level answer independent of identifying the specific entities: the WHERE clause requires BOTH lei_status non-null AND at least one parent-chain field non-null to become permanently ineligible; no code path in runPhase3 writes a parent-chain field without it being a correct terminal value, so an entity producing zero writes leaves all three parent-chain fields null, which alone satisfies the WHERE clause''s OR-fallback regardless of lei_status. Self-healing is structurally guaranteed by the query''s own design. On "ordinary explanation": the self-detail fetch explicitly throws on HTTP !ok, so an ordinary GLEIF 404/500/timeout produces the identical "zero writes, no exception" signature as a subrequest-cap failure would -- nothing in available evidence privileges one cause over the other. CONCLUSION: self-healing, low concern, no fast-follow warranted.

STEP 3 (INSERT-path test): satisfied using real, already-happened production evidence from the two live tests already run this session -- no new GLEIF calls or budget consumption needed. NINETY ONE GLOBAL STRATEGY FUND (entity_id 244947, LEI 2138004H9X7DRYXEU562) was created live via the create-parent-if-missing INSERT path when child entity 214499 resolved it as an ultimate-parent. Verified: name/normalized_name/type/lei/lei_status/country all sane and correctly extracted from GLEIF (name "NINETY ONE GLOBAL STRATEGY FUND", normalized "NINETY ONE GLOBAL STRATEGY", type holding, lei_status ACTIVE, country LU/Luxembourg, matching GLEIF''s real record). entity_relationships correctly linked: (parent_entity_id=244947, child_entity_id=214499, relationship_type=legal_parent, source=gleif). Duplicate check: exactly 1 entity_master row for this LEI. Orphan check: 0 orphan entity_relationships rows among all relationships created in the test window (checked broadly, not just this one pair). BONUS live evidence beyond what was asked: this same new parent entity was picked up again by the very next Phase 3 invocation (the hardening-checkpoint test, ~1hr later) and correctly reached a terminal state (direct_parent_exception=NO_LINK_DECLARED, its own GLEIF record has no parent declared) -- real, cross-invocation proof the self-healing/requeue mechanism works end-to-end with zero manual intervention. Also verified the "same parent found by multiple different children" case using LEGAL & GENERAL GROUP PLC (entity_id 26799, pre-existing): three distinct entity_relationships rows now exist for it (children 205955, 208286 from the first test; 206745 from the hardening test), zero duplicates, correctly enforced by the composite PRIMARY KEY (parent_entity_id, child_entity_id, relationship_type) -- no constraint violations, no double-counting across three separate discovery events spanning two different invocations.

CONCLUSION: the INSERT path -- previously completely untested in production -- is now confirmed correct on real data: sane new-entity creation, correct relationship linkage, no duplicates, no orphans, correct idempotent behavior when the same parent is rediscovered by different children across different invocations, and correct self-healing requeue of the newly-created entity itself. Not proceeding to Step 4 (6,265-row reset budget estimate) per instruction -- awaiting review.'
WHERE ticket_id = 'MA-SEP-009';
